<?php
if( function_exists('acf_add_local_field_group') ) {
    
    $sidebars_widgets = get_option( 'sidebars_widgets' );

    foreach ( $sidebars_widgets as $key => $sidebar ) {
        if (is_array($sidebar) && $sidebar) {
            $sidebars[$key] = $key;
        }
    }
    
    acf_add_local_field_group(array(
        'key' => 'tw_report_metabox',
        'title' => 'Тайлан, мэдээлэл тохиргоо',
        'fields' => array(
            array(
                'key' => 'field_reports_type',
                'label' => 'Тайлан, мэдээлэл төрөл',
                'name' => 'reports_type',
                'type' => 'radio',
                'instructions' => '',
                'required' => 1,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'choices' => array(
                    'default' => 'Гараар бичсэн',
                    'pdf' => 'PDF файл оруулах',
                ),
                'allow_null' => 0,
                'other_choice' => 0,
                'default_value' => '',
                'layout' => 'vertical',
                'return_format' => 'value',
                'save_other_choice' => 0,
            ),
            array(
                'key' => 'field_huuliin_togtool',
                'label' => 'Тайлан, мэдээлэл  тогтоол',
                'name' => 'huuliin_togtool',
                'type' => 'text',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => array(
                    array(
                        array(
                            'field' => 'field_reports_type',
                            'operator' => '==',
                            'value' => 'default',
                        ),
                    ),
                ),
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'default_value' => '',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
                'maxlength' => '',
            ),
            array(
                'key' => 'field_huuliin_image',
                'label' => 'Толгойн зураг',
                'name' => 'huuliin_image',
                'type' => 'image',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => array(
                    array(
                        array(
                            'field' => 'field_reports_type',
                            'operator' => '==',
                            'value' => 'default',
                        ),
                    ),
                ),
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'return_format' => 'url',
                'preview_size' => 'full',
                'library' => 'all',
                'min_width' => '',
                'min_height' => '',
                'min_size' => '',
                'max_width' => '',
                'max_height' => '',
                'max_size' => '',
                'mime_types' => '',
                'default_value' => 265,
            ),
            array(
                'key' => 'field_huuliin_date',
                'label' => 'Тайлан, мэдээлэл төслийн батлагдсан хугацаа',
                'name' => 'huuliin_date',
                'type' => 'date_picker',
                'instructions' => 'Батлагдсан өдрийг сонгоно уу!',
                'required' => 0,
                'conditional_logic' => array(
                    array(
                        array(
                            'field' => 'field_reports_type',
                            'operator' => '==',
                            'value' => 'default',
                        ),
                    ),
                ),
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'display_format' => 'Y оны m дугаар сарын d-ны өдөр',
                'return_format' => 'Y,m,d',
                'first_day' => 1,
            ),
            array(
                'key' => 'field_huuliin_location',
                'label' => 'Байршил',
                'name' => 'huuliin_location',
                'type' => 'text',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => array(
                    array(
                        array(
                            'field' => 'field_reports_type',
                            'operator' => '==',
                            'value' => 'default',
                        ),
                    ),
                ),
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'default_value' => '',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
                'maxlength' => '',
            ),
            array(
                'key' => 'field_huuliin_dugaar',
                'label' => 'Дугаар',
                'name' => 'huuliin_dugaar',
                'type' => 'text',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => array(
                    array(
                        array(
                            'field' => 'field_reports_type',
                            'operator' => '==',
                            'value' => 'default',
                        ),
                    ),
                ),
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'default_value' => '',
                'placeholder' => 'Дараах форматаар оруулна уу! (Дугаар 15 гэх мэт)',
                'prepend' => '',
                'append' => '',
                'maxlength' => '',
            ),
            array(
                'key' => 'field_huuliin_darga',
                'label' => 'Монгол улсын их хурлын дарга',
                'name' => 'huuliin_darga',
                'type' => 'text',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => array(
                    array(
                        array(
                            'field' => 'field_reports_type',
                            'operator' => '==',
                            'value' => 'default',
                        ),
                    ),
                ),
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'default_value' => '',
                'placeholder' => 'Дараах форматаар оруулна уу! (Монгол улсын их хурлын дарга гэх мэт)',
                'prepend' => '',
                'append' => '',
                'maxlength' => '',
            ),
            array(
                'key' => 'field_huuliin_darga_name',
                'label' => 'Монгол улсын их хурлын даргын нэр',
                'name' => 'huuliin_darga_name',
                'type' => 'text',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => array(
                    array(
                        array(
                            'field' => 'field_reports_type',
                            'operator' => '==',
                            'value' => 'default',
                        ),
                    ),
                ),
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'default_value' => '',
                'placeholder' => 'Дараах форматаар оруулна уу! (Н. БАГАБАНДИ гэх мэт)',
                'prepend' => '',
                'append' => '',
                'maxlength' => '',
            ),
            array(
                'key' => 'field_huuliin_surwalj',
                'label' => 'Эх сурвалж',
                'name' => 'huuliin_surwalj',
                'type' => 'text',
                'instructions' => '',
                'required' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'default_value' => 'Эх сурвалж - Legalinfo.mn',
                'placeholder' => 'Дараах форматаар оруулна уу! (Эх сурвалж - Legalinfo.mn гэх мэт)',
                'prepend' => '',
                'append' => '',
                'maxlength' => '',
            ),
            array(
                'key' => 'field_huuliin_surwalj_url',
                'label' => 'Эх сурвалж Холбоос оруулах',
                'name' => 'huuliin_surwalj_url',
                'type' => 'url',
                'instructions' => '',
                'required' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'default_value' => 'https://legalinfo.mn',
                'placeholder' => 'Сайтын хаягыг энд бичиж оруулна уу!',
            ),
            array(
                'key' => 'field_huuli_pdf',
                'label' => 'PDF Файл оруулах',
                'name' => 'huuli_pdf',
                'type' => 'file',
                'instructions' => '',
                'required' => 1,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'return_format' => 'array',
                'library' => 'all',
                'min_size' => '',
                'max_size' => '',
                'mime_types' => 'pdf',
                'conditional_logic' => array(
                    array(
                        array(
                            'field' => 'field_reports_type',
                            'operator' => '==',
                            'value' => 'pdf',
                        ),
                    ),
                ),
            ),
            array(
                'key' => 'field_page_sidebar',
                'label' => 'Sidebar?',
                'name' => 'page_sidebar',
                'type' => 'select',
                'instructions' => '',
                'required' => 1,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'choices' => array(
                    'disable' => 'Disable',
                    'enable' => 'Enable',
                ),
                'default_value' => '',
                'allow_null' => 0,
                'multiple' => 0,
                'ui' => 0,
                'return_format' => 'value',
                'ajax' => 0,
                'placeholder' => '',
            ),
            array(
                'key' => 'field_sidebar_widget',
                'label' => 'Select sidebar widget?',
                'name' => 'sidebar_widget',
                'type' => 'select',
                'instructions' => '',
                'required' => 1,
                'conditional_logic' => array(
                    array(
                        array(
                            'field' => 'field_page_sidebar',
                            'operator' => '==',
                            'value' => 'enable',
                        ),
                    ),
                ),
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'choices' => $sidebars,
                'default_value' => '',
                'allow_null' => 0,
                'multiple' => 0,
                'ui' => 0,
                'return_format' => 'value',
                'ajax' => 0,
                'placeholder' => '',
            ),
            array(
                'key' => 'field_page_content_width',
                'label' => 'Page content width?',
                'name' => 'page_content_width',
                'type' => 'select',
                'instructions' => '',
                'required' => 1,
                'conditional_logic' => array(
                    array(
                        array(
                            'field' => 'field_page_sidebar',
                            'operator' => '==',
                            'value' => 'enable',
                        ),
                    ),
                ),
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'choices' => array(
                    'uk-container-fullwidth' => '100% - Fullwidth ',
                    'uk-container-xlarge'    => '1800px - Extra Large ',
                    'uk-container-large'     => '1400px - Large ',
                    'default'                => '1170px - Boxed Stretch',
                    'uk-container-small'     => '900px - Small ',
                    'uk-container-xsmall'    => '600px - xSmall ',
                ),
                'default_value' => 'uk-container-large',
                'allow_null' => 0,
                'multiple' => 0,
                'ui' => 0,
                'return_format' => 'value',
                'ajax' => 0,
                'placeholder' => '',
            ),
            array(
                'key' => 'field_page_size',
                'label' => 'Page size?',
                'name' => 'page_size',
                'type' => 'select',
                'instructions' => '',
                'required' => 1,
                'conditional_logic' => array(
                    array(
                        array(
                            'field' => 'field_page_sidebar',
                            'operator' => '==',
                            'value' => 'enable',
                        ),
                    ),
                ),
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'choices' => array(
                    'uk-section-xsmall'          => '20px - Extra Small',
                    'uk-section-small'           => '40px - Small',
                    'uk-section-normal'          => '80px - Normal',
                    'uk-section-medium'          => '90px - Medium',
                    'default'                    => '110px - Default',
                    'uk-section-large'           => '140px - Large',
                    'uk-section-mlarge'          => '160px - Medium Large',
                    'uk-section-xlarge'          => '210px - Extra Large',
                    'uk-padding-remove-vertical' => '0 - Remove Padding',
                ),
                'default_value' => 'uk-section-small',
                'allow_null' => 0,
                'multiple' => 0,
                'ui' => 0,
                'return_format' => 'value',
                'ajax' => 0,
                'placeholder' => '',
            ),
            array(
                'key' => 'field_page_gutter',
                'label' => 'Page gutter?',
                'name' => 'page_gutter',
                'type' => 'select',
                'instructions' => '',
                'required' => 1,
                'conditional_logic' => array(
                    array(
                        array(
                            'field' => 'field_page_sidebar',
                            'operator' => '==',
                            'value' => 'enable',
                        ),
                    ),
                ),
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'choices' => array(
                    'uk-grid-xsmall'   => '10px - XSmall ',
                    'uk-grid-small'    => '15px - Small',
                    'uk-grid-medium'   => '30px - Medium',
                    'default'          => '40px - Default',
                    'uk-grid-large'    => '70px - Large',
                    'uk-grid-collapse' => '0 - Collapse',
                ),
                'default_value' => 'default',
                'allow_null' => 0,
                'multiple' => 0,
                'ui' => 0,
                'return_format' => 'value',
                'ajax' => 0,
                'placeholder' => '',
            ),
        ),
        'location' => array(
            array(
                array(
                    'param' => 'post_type',
                    'operator' => '==',
                    'value' => 'reports',
                ),
            ),
        ),
        'menu_order' => 0,
        'position' => 'normal',
        'style' => 'default',
        'label_placement' => 'top',
        'instruction_placement' => 'label',
        'hide_on_screen' => '',
        'active' => true,
        'description' => '',
    ));
}